---
title: "R Notebook"
output: html_notebook
---

```{r}
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/sign_weight.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/w_threshold.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/best_n.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/combined.R")
```

```{r}
mv_train<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/train2.csv",header = T, stringsAsFactors = F)
mv_test<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/test2.csv",header = T, stringsAsFactors = F)
```

```{r}
mv_train<-data.frame(mv_train[,-1],row.names = mv_train[,1])
mv_cor_train<- cor(t(mv_train[,-1]),use="pairwise.complete.obs",method="pearson")
```

```{r}
run.sign_weight=TRUE
run.w_threshold=TRUE 
run.best_n=TRUE
run.combined=TRUE
if(run.sign_weight){
  pearson_sw2<- sign_w(sw= mv_cor_train, data= mv_train)
}
if(run.w_threshold){
  r1<- cwt(pearson_sw2, t= 0.6)
}
if(run.best_n){
  r2<- best_n(pearson_sw2, n=10)
}
if(run.combined){
  r3<- combined(pearson_sw2, n=10, t=0.6)
}
```