---
title: "R Notebook"
output: html_notebook
---

```{r}
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/sign_weight.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/sign_weight1.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/w_threshold.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/best_n.R")
source("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/lib/combined.R")
```

```{r}
mv_train<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/train2.csv",header = T, stringsAsFactors = F)
mv_test<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/test2.csv",header = T, stringsAsFactors = F)
ms_train<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/MS_train2.csv",header = T, stringsAsFactors = F)
ms_test<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/MS_test2.csv",header = T, stringsAsFactors = F)
# ms_train<- ms_train[ ,-1]
# ms_test<- ms_test[ ,-1]
```

```{r}
mv_train<-data.frame(mv_train[,-1],row.names = mv_train[,1])
# mv_cor_train<- cor(t(mv_train[,-1]),use="pairwise.complete.obs",method="pearson")
ms_train<-data.frame(ms_train[,-1],row.names = ms_train[,1])
# ms_cor_train<- cor(t(ms_train[,-1]),use="pairwise.complete.obs",method="pearson")
```

```{r}
mse1<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/mse1.csv",header = T, stringsAsFactors = F)
mse2<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/mse2.csv",header = T, stringsAsFactors = F)
pearson1<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/pearson1.csv",header = T, stringsAsFactors = F)
pearson2<- read.csv("/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/data/pearson2.csv",header = T, stringsAsFactors = F)
```


```{r}
# run.sign_weight=TRUE
# run.w_threshold=TRUE 
# run.best_n=TRUE
# run.combined=TRUE
# if(run.sign_weight){
#   pearson_sw2<- sign_w(sw= mv_cor_train, data= mv_train)
# }
# if(run.w_threshold){
#   r1<- cwt(pearson_sw2, t= 0.6)
# }
# if(run.best_n){
#   r2<- best_n(pearson_sw2, n=10)
# }
# if(run.combined){
#   r3<- combined(pearson_sw2, n=10, t=0.6)
# }
```



```{r}
run.sign_weight=TRUE
run.sign_weight1=TRUE
run.w_threshold=TRUE 
run.best_n=TRUE
run.combined=TRUE
if(run.sign_weight){
  mse2.sw<- sign_w(sw= mse2[ ,-1], data= mv_train)
  pearson2.sw<- sign_w(sw= pearson2[ ,-1], data= mv_train)
}
if(run.sign_weight1){
  mse1.sw<- sign_w1(sw= mse1[ ,-1], data= ms_train)
  pearson1.sw<- sign_w1(sw= pearson1[ ,-1], data= ms_train)
}
# if(run.w_threshold){
# # ################dataset1#######################0.2,0.4,0.5,0.6
# #   # pearson1.wt0.5<-cwt(pearson1[ ,-1], t= 0.5)
# #   # pearson1.wt0.2<-cwt(pearson1[ ,-1], t= 0.2)
# #   # pearson1.wt0.4<-cwt(pearson1[ ,-1], t= 0.4)
# #   # pearson1.wt0.6<-cwt(pearson1[ ,-1], t= 0.6)
# #   pearson1.sw.wt0.05<- cwt(pearson1.sw, t= 0.05)
# #   pearson1.sw.wt0.02<- cwt(pearson1.sw, t= 0.02)
# #   pearson1.sw.wt0.04<- cwt(pearson1.sw, t= 0.04)
# #   pearson1.sw.wt0.06<- cwt(pearson1.sw, t= 0.06)
# # ################dataset2######################0.2,0.4,0.5,0.6
# #   # pearson2.wt0.5<-cwt(pearson2[ ,-1], t= 0.5)
# #   # pearson2.wt0.2<-cwt(pearson2[ ,-1], t= 0.2)
# #   # pearson2.wt0.4<-cwt(pearson2[ ,-1], t= 0.4)
# #   # pearson2.wt0.6<-cwt(pearson2[ ,-1], t= 0.6)
# #   # pearson2.sw.wt0.5<- cwt(pearson2.sw, t= 0.5)
# #   # pearson2.sw.wt0.2<- cwt(pearson2.sw, t= 0.2)
# #   # pearson2.sw.wt0.4<- cwt(pearson2.sw, t= 0.4)
# #   # pearson2.sw.wt0.6<- cwt(pearson2.sw, t= 0.6)
# #################dataset1######################mse1:0-0.1822:0.05
#   mse1.wt0.04<- cwt(mse1[ ,-1], t=0.04)
#   mse1.wt0.05<- cwt(mse1[ ,-1], t=0.05)
#   mse1.sw.wt0.002<- cwt(mse1.sw, t=0.002)
# # #################dataset2######################mse:0-25:5
#   mse2.wt0.3<- cwt(mse2[ ,-1], t=0.3)
#   mse2.wt0.5<- cwt(mse2[ ,-1], t=0.5)
#   mse2.sw.wt0.3<- cwt(mse2.sw, t =0.3)
#   mse2.sw.wt0.5<- cwt(mse2.sw, t =0.5)
# }
```

```{r}
# write.csv(pearson1.wt0.5, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.wt0.5.csv")
# write.csv(pearson1.wt0.2, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.wt0.2.csv")
# write.csv(pearson1.wt0.4, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.wt0.4.csv")
# write.csv(pearson1.wt0.6, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.wt0.6.csv")
# write.csv(pearson1.sw.wt0.05, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.wt0.05.csv")
# write.csv(pearson1.sw.wt0.04, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.wt0.04.csv")
# write.csv(pearson1.sw.wt0.02, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.wt0.02.csv")
# write.csv(pearson1.sw.wt0.06, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.wt0.06.csv")

# write.csv(pearson2.wt0.5, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.wt0.5.csv")
# write.csv(pearson2.wt0.2, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.wt0.2.csv")
# write.csv(pearson2.wt0.4, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.wt0.4.csv")
# write.csv(pearson2.wt0.6, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.wt0.6.csv")
# write.csv(pearson2.sw.wt0.5, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.wt0.5.csv")
# write.csv(pearson2.sw.wt0.4, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.wt0.4.csv")
# write.csv(pearson2.sw.wt0.2, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.wt0.2.csv")
# write.csv(pearson2.sw.wt0.6, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.wt0.6.csv")
write.csv(mse1.wt0.04, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.wt0.04.csv")
write.csv(mse1.wt0.05, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.wt0.05.csv")
write.csv(mse1.sw.wt0.002, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.sw.wt0.002.csv")
write.csv(mse2.wt0.3, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.wt0.3.csv")
write.csv(mse2.wt0.5, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.wt0.5.csv")
write.csv(mse2.sw.wt0.3, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.sw.wt0.3.csv")
write.csv(mse2.sw.wt0.5, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.sw.wt0.5.csv")
```

```{r}
if(run.best_n){
#################dataset1####################n= 50,100,150
  # pearson1.bn50<- best_n(pearson1[ ,-1], 50)
  # pearson1.bn50<- data.frame(pearson1.bn50, row.names = pearson1[ ,1])
  # pearson1.bn100<- best_n(pearson1[ ,-1], 100)
  # pearson1.bn100<- data.frame(pearson1.bn100, row.names = pearson1[ ,1])
  # pearson1.bn150<- best_n(pearson1[ ,-1], 150)
  # pearson1.bn150<- data.frame(pearson1.bn150, row.names = pearson1[ ,1])
  # pearson1.sw.bn50<- best_n(pearson1.sw, 50)
  # pearson1.sw.bn50<- data.frame(pearson1.sw.bn50, row.names = pearson1[ ,1])
  # pearson1.sw.bn100<- best_n(pearson1.sw, 100)
  # pearson1.sw.bn100<- data.frame(pearson1.sw.bn100, row.names = pearson1[ ,1])
  # pearson1.sw.bn150<- best_n(pearson1.sw, 150)
  # pearson1.sw.bn150<- data.frame(pearson1.sw.bn150, row.names = pearson1[ ,1])
###############dataset2####################n= 50,100,150
  pearson2.bn50<- best_n(pearson2[ ,-1], 50)
  pearson2.bn50<-data.frame(pearson2.bn50, row.names = pearson2[ ,1])
  pearson2.bn100<- best_n(pearson2[ ,-1], 100)
  pearson2.bn100<-data.frame(pearson2.bn100, row.names = pearson2[ ,1])
  pearson2.bn150<- best_n(pearson2[ ,-1], 150)
  pearson2.bn150<-data.frame(pearson2.bn150, row.names = pearson2[ ,1])
  pearson2.sw.bn50<- best_n(pearson2.sw, 50)
  pearson2.sw.bn50<- data.frame(pearson2.sw.bn50,row.names = pearson2[ ,1])
  pearson2.sw.bn100<- best_n(pearson2.sw, 100)
  pearson2.sw.bn100<- data.frame(pearson2.sw.bn100,row.names = pearson2[ ,1])
  pearson2.sw.bn150<- best_n(pearson2.sw, 150)
  pearson2.sw.bn150<- data.frame(pearson2.sw.bn150,row.names = pearson2[ ,1])
# ##############dataset1###################n= 100,150
#   mse1.bn100<- best_n(mse1[ ,-1],100)
#   mse1.bn150<- best_n(mse1[ ,-1],150)
#   mse1.sw.bn100<- best_n(mse1.sw,100)
#   mse1.sw.bn150<- best_n(mse1.sw,150)
# ##############dataset2##############n=100,150
#   mse2.bn100<- best_n(mse2[ ,-1],100)
#   mse2.bn150<- best_n(mse2[ ,-1],150)
#   mse2.sw.bn100<- best_n(mse2.sw,100)
#   mse2.sw.bn150<- best_n(mse2.sw,150)
}
```

```{r}
write.csv(pearson1.bn50,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.bn50.csv")
write.csv(pearson1.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.bn100.csv")
write.csv(pearson1.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.bn150.csv")
write.csv(pearson1.sw.bn50,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.bn50.csv")
write.csv(pearson1.sw.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.bn100.csv")
write.csv(pearson1.sw.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.bn150.csv")
write.csv(pearson2.bn50,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.bn50.csv")
write.csv(pearson2.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.bn100.csv")
write.csv(pearson2.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.bn150.csv")
write.csv(pearson2.sw.bn50,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.bn50.csv")
write.csv(pearson2.sw.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.bn100.csv")
write.csv(pearson2.sw.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.bn150.csv")
# write.csv(mse1.bn100, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.bn100.csv")
# write.csv(mse1.bn150, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.bn150.csv")
# write.csv(mse1.sw.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.sw.bn100.csv")
# write.csv(mse1.sw.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse1.sw.bn150.csv")
# 
# write.csv(mse2.bn100, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.bn100.csv")
# write.csv(mse2.bn150, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.bn150.csv")
# write.csv(mse2.sw.bn100,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.sw.bn100.csv")
# write.csv(mse2.sw.bn150,"/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/mse2.sw.bn150.csv")
```

```{r}
if(run.combined){
  pearson1.com<- combined(pearson1, n=150, t=0.4)
  pearson1.com<- data.frame(pearson1.com, row.names = pearson1[ ,1])
  pearson2.com<- combined(pearson2, n=150, t=0.4)
  pearson2.com<- data.frame(pearson2.com, row.names = pearson2[ ,1])
  pearson1.sw.com<- combined(pearson1.sw, n=150, t=0.02)
  pearson1.sw.com<- data.frame(pearson1.sw.com, row.names = pearson1[ ,1])
  pearson2.sw.com<- combined(pearson2.sw, n=100, t=0.4)
  pearson2.sw.com<- data.frame(pearson2.sw.com, row.names = pearson2[ ,1])
}
```

```{r}
write.csv(pearson1.com, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.com")
write.csv(pearson2.com, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.com")
write.csv(pearson1.sw.com, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson1.sw.com")
write.csv(pearson2.sw.com, "/Users/linhan/Desktop/semester3/ADS/fall2017-project4-group4/output/pearson2.sw.com")
```