setwd("D:/Fall 2017/ADS/eachmovie_sample")
train2<-read.csv("train2.csv",header=T)
train2<-data.frame(train2[,-1],row.names = train2[,1])
mv_cor<- cor(t(train2[,-1]),use="pairwise.complete.obs",method="pearson")
write.csv(mv_cor,"pearson2.csv")